### ISSUE TITLE
Stopping Mycroft from Narrating last querry

### ISSUE THREAD

**Issue by rajdpandey** [MycroftAI/skill-wiki#27]
Hi all,

I am using picroft on Raspberry Pi 3B+ and there is an issue I wanted to ask about and how to achieve that.

Example:

User: Hey Mycroft tell me about the Himalayas?
Mycroft: Starts narrating answer.
(Between the Narration)
User asks: Hey Mycroft tell me about America?

Then Mycroft should stop tell me about Himalaya's and should tell me about America.

But right now it first completes whole Himalaya's narration and then starts telling me about America.

I don't want to manually say Hey Mycroft stop.

It should be automatic.

So how can I make this?

**Comment by maximlomans** [comment]
did you try :
hey mycroft, forget about'it, tell me about america instead 
; )

**Comment by rajdpandey** [comment]
No, I haven't. but I will try it now. And also do you have an idea where to change or what function is used to make Mycroft listen for a specific time from within a skill.

**Comment by krisgesling** [comment]
Hey Raj, I think that was a joke above. There's currently no way to achieve this. 

In terms of your new question, do you mean the length of time Mycroft listens for? Currently this is 10 seconds and our servers won't accept longer audio chunks.

**Comment by rajdpandey** [comment]
Oh, thanks. I meant like if I say some command and Mycroft will execute that command but after executing it should listen for some second if user gives another command for that. Means for every command user have to say Hey Mycroft but with this, it will be like they will say one command and after execution, if they want to give another command they can within the period of time of listening after that they have to again Hey Mycroft for command. 

I hope I have clearly explained my question.

**Comment by krisgesling** [comment]
This would require modifying mycroft-core, it's not functionality that I could see being included as a default.

I'm going to close this issue but happy to keep chatting about possibilities over in Mycorft Chat.

**Comment by rajdpandey** [comment]
Ok Sir, no problem. I will update here If I have any idea that can be included in Mycroft.
