### ISSUE TITLE
Font size Hack does not work on Mark-2 prototype

### ISSUE THREAD

**Issue by guhl** [MycroftAI/skill-wiki#43]
On my Mark-2 prototype using the BOM display the hack for the fontsize does not work well (The font is super small).
I fixed this differently in WikipediaDelegate.qml:
`...`
`import QtQuick.Window 2.2`
`...`
`font.pointSize: Math.floor(20 * 4 / Screen.pixelDensity)`
`...`

This provides the same font size on Neo running in a VirtualMachine and on the device.

**Comment by notmart** [comment]
can you try starting the gui app with the following environmant variable?
QT_SCALE_FACTOR=2 (or even higher numbers if necessary)

**Comment by guhl** [comment]
> can you try starting the gui app with the following environmant variable?
> QT_SCALE_FACTOR=2 (or even higher numbers if necessary)

Thanks for the feedback but:
while QT_SCALE_FACTOR=2 does give a reasonable font size in this wiki skill it changes the scaling of all GUI elements and for example the clock of the mark2 idle screen now only shows the last digit of the hour and the first of the minute (atm it shows 5:0 because is is 15:04)
I would not count this a proper fix.

**Comment by notmart** [comment]
is it using qeglfs QPA?

**Comment by notmart** [comment]
in eglfs may also help playing with QT_QPA_EGLFS_PHYSICAL_WIDTH (and height) in case the proper size hasn't been detected

**Comment by krisgesling** [comment]
Hack removed in #54 

Still plenty of work to be done on the UI of this Skill but these are covered in other issues.
