### ISSUE TITLE
Handling nested descriptions for Summary

### ISSUE THREAD

**Issue by emphasize** [MycroftAI/skill-wiki#44]
I think it's not uncommon that you will find nested descriptions that should be dumped ([#](https://github.com/MycroftAI/skill-wiki/blob/c1504a9264e7a329934659b68096031a8a63a35d/__init__.py#L156)/[#](https://github.com/MycroftAI/skill-wiki/blob/c1504a9264e7a329934659b68096031a8a63a35d/__init__.py#L88)) in the summary

ex (german): (auch Bert Brecht; * 10. Februar 1898 als Eugen Berthold Friedrich Brecht in Augsburg; † 14. August 1956 in Berlin (Ost))

The regex pattern in place will carve out from the first "(" to the first ")" leaving the summary like "Bertolt Brecht ) war ein einflussreicher" _(Actually that's not the best example, but in case something's following the first ")" it would reside in the summary)_

To handle nested descriptions the code should be changed to
```
pattern = r"\([^()]*\)|/[^/]*/"     #note that an "(" is added to [^)]

while re.findall(pattern, summary):
    summary = re.sub(pattern, "", summary)
```

If the pattern should be expanded to search for (nested) "[" or "]" (which it should)
`
pattern = r"\([^()]*\)|/[^/]*/|\[[^\[\]]*\]"`

It also seems to be beneficial if the pattern's looking for a space in front of (,[,/ to reduce false positives:

`pattern = r"\s\([^()]*\)|\s/[^/]*/|\s\[[^\[\]]*\]"`

**Comment by krisgesling** [comment]
Hey, I think I've addressed this in #70 

It will now remove any nested parentheses from the summary.

Feedback most welcome if you want to give it a try :)
