### ISSUE TITLE
Using textextraction method other than "exsentences" (wikipedia.summary)

### ISSUE THREAD

**Issue by emphasize** [MycroftAI/skill-wiki#45]
While at times this works reasonably well, there are many cases the summary will be completly butchered.

([TextExtracts API](https://www.mediawiki.org/wiki/Extension:TextExtracts))

> There are various things to be aware of when using the API
> 
> We do not recommend the usage of `exsentences`. It does not work for HTML extracts and there are many edge cases for which it doesn't exist. **For example "Arm. gen. Ing. John Smith was a soldier." will be treated as 4 sentences. We do not plan to fix this.** 

_In our case the output would be "Arm. gen." if passing_ `lines = 2` ([#](https://github.com/MycroftAI/skill-wiki/blob/c1504a9264e7a329934659b68096031a8a63a35d/__init__.py#L142))

[wikipedia.summary](https://github.com/goldsmith/Wikipedia/blob/2065c568502b19b8634241b47fd96930d1bf948d/wikipedia/wikipedia.py#L215)

**Comment by emphasize** [comment]
to add another example where this parallels with the issue #44 

Asking for George Washington in wikipedia results in output:
_"George Washington [ˈwɒʃɪŋtən] im Westmoreland County, Kolonie Virginia; † 14."_ :dizzy_face:

Source:
George Washington [ˈwɒʃɪŋtən] ~~(* 22. Februar 1732[1] auf dem Gutshof Wakefield (auch „Pope’s Plantation“ genannt)~~ im Westmoreland County, Kolonie Virginia; † 14. ~~Dezember 1799 auf seinem Gut Mount Vernon, Virginia) war ...~~

**Comment by krisgesling** [comment]
Hey there, thanks for doing some digging on this. 

I might ask in our dev channel on Mycroft Chat to see if anyone has a recommendation for other packages to use

**Comment by emphasize** [comment]
In the same package the call `wikipedia.page("George_Washington").content` could be an option.

While i'm sympathetic to the incremental approach in place, it has its downsides (constant checking for len - in cases i described, limited to 10 sentences total, ...) and if you want to get to the meat of the article...

Page.content fetches the whole content which would be easier to post-process.

**Comment by krisgesling** [comment]
Jarbas just reminded me of his package: https://github.com/HelloChatterbox/wikipedia_for_humans

Would be a good one to test out

**Comment by krisgesling** [comment]
Fixed in #70 also - the new package we're using pymediawiki contains a `.summarize()` method. We then clean it up a bit further from there.

In the case of "George Washington" we get: 
> George Washington was an American political leader, military general, statesman, and Founding Father, who served as the first president of the United States from 1789 to 1797.
